platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'CXDownload_Example' do
  use_frameworks!
  
  pod 'CXDownload', :path => '../'
  pod 'FMDB'
  pod 'AFNetworking'
  
  target 'CXDownload_Tests' do
    inherit! :search_paths
    
  end
end
