platform :ios, '11.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'CXDownload_Example' do
  use_frameworks!
  
  pod 'CXDownload', :path => '../'
  pod 'FMDB'
  pod 'AFNetworking'
  
  target 'CXDownload_Tests' do
    inherit! :search_paths
    
  end
end
